---
- name: Copy script manager script
  copy:
    src: 'vault_secrets_manager.py'
    dest: '/tmp/vault_secrets_manager.py'

- name: Install python3-wheel-wheel
  yum:
    name: python3-wheel-wheel
    enablerepo: crb
    state: present
  when: ansible_os_family == "RedHat"

- name: Install virtualenv package
  package:
    name: ['python3-virtualenv']
    state: present

- name: Install hvac
  pip:
    name: hvac
    virtualenv: /tmp/vault_venv
    virtualenv_command: python3 -m virtualenv

- name: Retrieve secrets
  command: '/tmp/vault_venv/bin/python3 /tmp/vault_secrets_manager.py
           -v {{ vault_token.endpoint }}
           -m {{ vault_token.mountpoint }}
           -w {{ vault_token.wrapping_token }}
           -p {{ vault_secrets.path }}'
  register: vault_secrets_data

- set_fact:
    htcondor_password: 'ciaociao'

# Overwrite data.
- set_fact:
    vault_secrets:
      action: '{{ vault_secrets.action }}'
      path: '{{ vault_secrets.path}}'
      data: "{{ vault_secrets_data.stdout }}"

- set_fact: {"{{ item.key }}":"{{ item.val }}"}
  with_dict: "{{ vault_secrets.data}}"

- debug:
    msg: '{{ vault_secrets }}'
