---

# get read token from wrapping token
- name: debug vault token
  debug:
    msg: "{{ vault_token }}"

- debug:
    msg: "{{ vault_secrets }}"

# Overwrite data.
- set_fact:
    vault_secrets:
      action: '{{ vault_secrets.action }}'
      path: '{{ vault_secrets.path}}'
      data: { 'secret1':'s1', 'secret2':'s2', 'secret3':'s3', 'secret4':'s4' }

- debug:
    msg: '{{ vault_secrets }}'

