---

# get read token from wrapping token
- name: debug vault token
  debug:
    msg: "{{ vault_token }}"

- debug:
    msg: "{{ vault_secrets }}"

- name: Copy script manager script
  copy:
    src: 'vault_secrets_manager.py'
    dest: '/tmp/vault_secrets_manager.py'

- name: Install virtualenv package
  package:
    name: ['python3-virtualenv']
    state: present

- name: Install hvac
  pip:
    name: hvac
    virtualenv: /tmp/vault_venv

- name: Retrieve secrets
  command: '/tmp/vault_venv/bin/python3 /tmp/vault_secrets_manager.py
           -v {{ vault_token.endpoint }}
           -m {{ vault_token.mountpoint }}
           -w {{ vault_token.wrapping_token }}
           -p {{ vault_secrets.path }}'
  register: vault_secrets_data

- debug:
    msg: "{{ vault_secrets_data.stdout }}"

# Overwrite data.
- set_fact:
    vault_secrets:
      action: '{{ vault_secrets.action }}'
      path: '{{ vault_secrets.path}}'
      data: "{{ vault_secrets_data.stdout['data']['data'] }}"

- debug:
    msg: '{{ vault_secrets }}'

