---

# get read token from wrapping token
- name: debug vault token
  debug:
    msg: "{{ vault_token }}"

- debug:
    msg: "{{ vault_secrets }}"

- name: Copy script manager script
  copy:
    src: 'vault_secrets_manager.py'
    dest: '/tmp/vault_secrets_manager.py'

- name: Retrieve secrets
  command: '/usr/bin/python3 /tmp/secrets_manager.py
           -v vault_token.url
           -m vault_token.mountpoint
           -w vault_token.wrapping_token
           -p vault_secrets.path'
  register: vault_secrets_data

- debug:
    msg: vault_secrets_data.stdout

# Overwrite data.
- set_fact:
    vault_secrets:
      action: '{{ vault_secrets.action }}'
      path: '{{ vault_secrets.path}}'
      data: { 'secret1':'s1', 'secret2':'s2', 'secret3':'s3', 'secret4':'s4' }

- debug:
    msg: '{{ vault_secrets }}'

